Add x-mitre-data-component
OTRF/ATTACK-Python-Client pull request #37
Opened 2021-10-31 11:07 UTC by ZikyHD

Add :
- data_component_stix_mapping
- get_enterprise_data_components()
- get_data_components() (maybe in the future)
- get_techniques_detected_by_all_data_components()
- get_techniques_detected_by_data_component()
- get_data_component_by_technique()

2021-11-02 01:46 UTC, Cyb3rWard0g commented
Once again @ZikyHD ! Thank you very much for taking the time to do this! It looks good to me just by going through the code. I have to test your branch on my dev vm. I will be doing that on Friday this week. I will merge after that. 

Thank you again! 🍻

2021-11-17 19:45 UTC, ZikyHD commented
@Cyb3rWard0g any update on my proposal ? 😅

2022-01-06 03:40 UTC, Cyb3rPandaH commented
Hey @ZikyHD , hope everything is going well.

Sorry for the late reply, @Cyb3rWard0g and I are reviewing the PR. We will merge it over the weekend 👍 

Thank you again for your contribution guys 🙏

2022-01-06 18:30 UTC, Cyb3rPandaH commented
Quick question @ZikyHD 

What is the idea behind the function **get_techniques_detected_by_all_data_components** (Line 1479). Is it to get all techniques that have data components?

Thanks,

Jose

2022-01-06 19:21 UTC, Cyb3rWard0g requested changes
Hello @ZikyHD ! Thank you again! @Cyb3rPandaH  and I are working on it at the moment. These two functions are missing. I was wondering if maybe the code was not committed as part of the PR or maybe data components do not exist yet in ICS and mobile data. We are going to check that out that too right now.

2022-01-06 19:21 UTC, Cyb3rWard0g commented on attackcti/attack_api.py
> +        mobile_data_components = self.get_mobile_data_components()
missing get_mobile_data_components()

2022-01-06 19:21 UTC, Cyb3rWard0g commented on attackcti/attack_api.py
> +        ics_data_components = self.get_ics_data_components()
missing get_ics_data_components()

2022-01-06 22:40 UTC, Cyb3rWard0g commented on attackcti/attack_api.py
> +        ics_data_components = self.get_ics_data_components()
just validated that there are not ICS data components.

2022-01-06 22:40 UTC, Cyb3rWard0g commented on attackcti/attack_api.py
> +        mobile_data_components = self.get_mobile_data_components()
just validated that there are not data components for mobile

2022-01-06 22:44 UTC, Cyb3rWard0g commented
Thank you @ZikyHD ! I will accept the PR and comment out the functions that do not retrieve data components from Mobile and ICS inside of get_data_components(). 

Thank you again for the contribution and your patience! We really appreciate it!

2022-01-06 22:44 UTC, merged